Repository UOS2021/U.O.S-Mobile, pull requests merged in 2021-08, with the labels that each got.

#13 Modify Lobby,Login,Intro Activity
  .idea/misc.xml
  app/src/main/gen/com/uof/uof_mobile/BuildConfig.java
  app/src/main/gen/com/uof/uof_mobile/Manifest.java
  app/src/main/gen/com/uof/uof_mobile/R.java
  app/src/main/res/drawable-v24/qrcode.jpg
  app/src/main/res/layout/activity_intro.xml
  app/src/main/res/layout/activity_lobby.xml
  app/src/main/res/layout/activity_login.xml
Labels: 개발환경, 디자인

#14 공유 불필요 파일 및 .gitignore 적용
  .idea/.gitignore
  .idea/misc.xml
  app/src/main/java/com/uof/uof_mobile/OrderListActivity.java
  app/src/main/res/layout/activity_orderlist.xml
Labels: 문서

#15 LobbyActivity에서 다른 Activity로 화면 전환 구현
  app/src/main/java/com/uof/uof_mobile/LobbyActivity.java
  app/src/main/res/layout/activity_lobby.xml
Labels: 기능, 디자인

#21 U.O.F-Mobile <-> 테스트용 외부서버 로그인 및 회원가입 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/uof/uof_mobile/CardActivity.java
  app/src/main/java/com/uof/uof_mobile/HttpManager.java
  app/src/main/java/com/uof/uof_mobile/IntroActivity.java
  app/src/main/java/com/uof/uof_mobile/LobbyActivity.java
  app/src/main/java/com/uof/uof_mobile/LoginActivity.java
  app/src/main/java/com/uof/uof_mobile/OrderListActivity.java
  app/src/main/java/com/uof/uof_mobile/OrderingActivity.java
  app/src/main/java/com/uof/uof_mobile/PayActivity.java
  app/src/main/java/com/uof/uof_mobile/QRRecognitionActivity.java
  app/src/main/java/com/uof/uof_mobile/SettingActivity.java
  app/src/main/java/com/uof/uof_mobile/UofSocket.java
  app/src/main/res/layout/activity_card.xml
  app/src/main/res/layout/activity_lobby.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_ordering.xml
  app/src/main/res/layout/activity_orderlist.xml
  app/src/main/res/layout/activity_qrrecognition.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/xml/network_security_config.xml
Labels: 기능, 디자인, 코드 최적화

#22 LoginActivity 내 TextInputLayout 오류 메세지 표시
  app/src/main/java/com/uof/uof_mobile/Constants.java
  app/src/main/java/com/uof/uof_mobile/LoginActivity.java
  app/src/main/java/com/uof/uof_mobile/UofSocket.java
  app/src/main/res/layout/activity_login.xml
Labels: 기능, 제안

#24 사업자용 Activity 및 회원가입 Activity 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/uof/uof_mobile/OwnerLobbyActivity.java
  app/src/main/java/com/uof/uof_mobile/OwnerQRRecognitionActivity.java
  app/src/main/java/com/uof/uof_mobile/OwnerSettingActivity.java
  app/src/main/java/com/uof/uof_mobile/RegisterActivity.java
  app/src/main/res/layout/activity_ownerlobby.xml
  app/src/main/res/layout/activity_ownerqrrecognition.xml
  app/src/main/res/layout/activity_ownersetting.xml
  app/src/main/res/layout/activity_register.xml
Labels: 기능, 디자인

#25 QR 코드 스캐너 구현
  app/build.gradle
  app/src/main/java/com/uof/uof_mobile/LobbyActivity.java
  app/src/main/java/com/uof/uof_mobile/QRRecognitionActivity.java
  app/src/main/res/layout/activity_lobby.xml
  gradle.properties
Labels: 기능

#26 Hotfix Change orientation
  app/src/main/AndroidManifest.xml
Labels: 수정

#28 전반적인 회원가입 액티비티 디자인 수정, 기능 추가
  app/src/main/java/com/uof/uof_mobile/LoginActivity.java
  app/src/main/java/com/uof/uof_mobile/RegisterActivity.java
  app/src/main/res/drawable/box_border.xml
  app/src/main/res/drawable/spinner_background.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/values/array.xml
Labels: 구성, 기능, 디자인

#29 U.O.F-Mobile 사용자별 회원가입 기능 구현
  app/src/main/java/com/uof/uof_mobile/LobbyActivity.java
  app/src/main/java/com/uof/uof_mobile/LoginActivity.java
  app/src/main/java/com/uof/uof_mobile/OwnerLobbyActivity.java
  app/src/main/java/com/uof/uof_mobile/OwnerQRRecognitionActivity.java
  app/src/main/java/com/uof/uof_mobile/OwnerSettingActivity.java
  app/src/main/java/com/uof/uof_mobile/QRRecognitionActivity.java
  app/src/main/java/com/uof/uof_mobile/RegisterActivity.java
  app/src/main/java/com/uof/uof_mobile/RegisterTypeDialog.java
  app/src/main/java/com/uof/uof_mobile/RegisterTypeDialogListener.java
  app/src/main/res/color/selector_textinputlayout_register.xml
  app/src/main/res/drawable/background_registertypespinner.xml
  app/src/main/res/drawable/border_licenseimage.xml
  app/src/main/res/drawable/border_registertypedialog.xml
  app/src/main/res/drawable/box_border.xml
  app/src/main/res/layout/activity_ownerlobby.xml
  app/src/main/res/layout/activity_ownerqrrecognition.xml
  app/src/main/res/layout/activity_ownersetting.xml
  app/src/main/res/layout/activity_pay.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/layout/dialog_registertype.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/array.xml
  app/src/main/res/values/themes.xml
Labels: 구현 필요, 기능, 디자인, 코드 최적화

#30 Hotfix Change JSON Elements
  app/src/main/java/com/uof/uof_mobile/RegisterActivity.java
Labels: 수정

#31 Hotfix Change JSON Elements
  app/src/main/java/com/uof/uof_mobile/RegisterActivity.java
Labels: 수정

#32 [U.O.F-Mobile] Request, Response 코드 적용 및 TextInputLayout 오류 수정
  app/src/main/java/com/uof/uof_mobile/Constants.java
  app/src/main/java/com/uof/uof_mobile/LoginActivity.java
  app/src/main/java/com/uof/uof_mobile/RegisterActivity.java
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_register.xml
Labels: 오류해결, 기능

#33 [U.O.F-Mobile] QR코드 스캔 데이터 분리 및 SettingActivity 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/uof/uof_mobile/QRRecognitionActivity.java
  app/src/main/java/com/uof/uof_mobile/SettingPreferenceFragment.java
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/xml/settings_preference.xml
Labels: 기능, 디자인, 수정, 구현 필요

#34 [U.O.F-Mobile] 파트너 회원가입 시 회사 정보 입력 레이아웃 구분, 로그인 시 체크박스 구현
  app/src/main/java/com/uof/uof_mobile/LoginActivity.java
  app/src/main/java/com/uof/uof_mobile/RegisterActivity.java
  app/src/main/res/drawable/arrow_drop_down.png
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_register.xml
Labels: 기능, 디자인, 구현 필요

#35 [U.O.F-Mobile] Setting Preference Key 정리 및 Package 구분
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/uof/uof_mobile/SettingPreferenceFragment.java
  app/src/main/java/com/uof/uof_mobile/activity/CardActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/IntroActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/LobbyActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/LoginActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/OrderListActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/OrderingActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/OwnerLobbyActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/OwnerQRRecognitionActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/OwnerSettingActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/PayActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/QRRecognitionActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/RegisterActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/SettingActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/SocketTestActivity.java
  app/src/main/java/com/uof/uof_mobile/dialog/RegisterTypeDialog.java
  app/src/main/java/com/uof/uof_mobile/dialog/RegisterTypeDialogListener.java
  app/src/main/java/com/uof/uof_mobile/fragment/SettingPreferenceFragment.java
  app/src/main/java/com/uof/uof_mobile/manager/HttpManager.java
  app/src/main/java/com/uof/uof_mobile/manager/SocketManager.java
  app/src/main/res/layout/activity_card.xml
  app/src/main/res/layout/activity_intro.xml
  app/src/main/res/layout/activity_lobby.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_ordering.xml
  app/src/main/res/layout/activity_orderlist.xml
  app/src/main/res/layout/activity_ownerlobby.xml
  app/src/main/res/layout/activity_ownerqrrecognition.xml
  app/src/main/res/layout/activity_ownersetting.xml
  app/src/main/res/layout/activity_pay.xml
  app/src/main/res/layout/activity_qrrecognition.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/activity_sockettest.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/settings_preference.xml
Labels: 코드 최적화, 기능

#36 Hotfix Add Passing Button & Modify Layout configuration
  app/src/main/java/com/uof/uof_mobile/activity/LoginActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/RegisterActivity.java
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_register.xml
Labels: 오류, 수정

#37 [U.O.F Mobile] Hotfix Delete unused lines
  app/src/main/java/com/uof/uof_mobile/activity/RegisterActivity.java
  app/src/main/res/layout/activity_register.xml
Labels: 기능, 수정

#38 [U.O.F Mobile] 로비 액티비티 리스트 뷰 생성 및 버튼 아이콘 변경
  app/src/main/java/com/uof/uof_mobile/activity/LobbyActivity.java
  app/src/main/java/com/uof/uof_mobile/listview/LobbyListViewItem.java
  app/src/main/java/com/uof/uof_mobile/listview/LobbyListViewItemAdapter.java
  app/src/main/res/drawable-v24/card_icon.png
  app/src/main/res/drawable-v24/listview_border.xml
  app/src/main/res/drawable-v24/orderlist_icon.png
  app/src/main/res/drawable-v24/setting_icon.png
  app/src/main/res/layout/activity_lobby.xml
  app/src/main/res/layout/rows_noworderlist.xml
Labels: 기능, 디자인, 구성

#39 [U.O.F-Mobile] 설정 기능 구현 및 디자인 테마 설정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/uof/uof_mobile/Constants.java
  app/src/main/java/com/uof/uof_mobile/activity/LobbyActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/LoginActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/QRRecognitionActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/RegisterActivity.java
  app/src/main/java/com/uof/uof_mobile/dialog/ChangePhoneDialog.java
  app/src/main/java/com/uof/uof_mobile/dialog/ChangePwDialog.java
  app/src/main/java/com/uof/uof_mobile/dialog/CheckPwDialog.java
  app/src/main/java/com/uof/uof_mobile/fragment/SettingPreferenceFragment.java
  app/src/main/res/color/selector_textinputlayout_register.xml
  app/src/main/res/drawable-v24/listview_border.xml
  app/src/main/res/drawable/icon_btnback.png
  app/src/main/res/drawable/icon_btnclose.png
  app/src/main/res/drawable/ripple_btnback.xml
  app/src/main/res/drawable/ripple_btnclose.xml
  app/src/main/res/layout/activity_lobby.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/dialog_changephone.xml
  app/src/main/res/layout/dialog_changepw.xml
  app/src/main/res/layout/dialog_checkpw.xml
  app/src/main/res/layout/rows_noworderlist.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/settings_preference.xml
Labels: 코드 최적화, 기능, 디자인, 구성, 구현 필요

#40 Hotfix: Add close function into register appbar button
  app/src/main/java/com/uof/uof_mobile/activity/RegisterActivity.java
  app/src/main/res/layout/activity_register.xml
Labels: 기능, 수정

#41 [U.O.F Mobile] Dialog 풀 스크린 적용, 낮밤에 따른 아이콘 변경
  app/src/main/java/com/uof/uof_mobile/activity/LoginActivity.java
  app/src/main/java/com/uof/uof_mobile/dialog/ChangePhoneDialog.java
  app/src/main/java/com/uof/uof_mobile/dialog/ChangePwDialog.java
  app/src/main/res/drawable/icon_btnback.png
  app/src/main/res/drawable/icon_btnback_day.png
  app/src/main/res/drawable/icon_btnback_night.png
  app/src/main/res/drawable/icon_btnclose.png
  app/src/main/res/drawable/icon_btnclose_day.png
  app/src/main/res/drawable/icon_btnclose_night.png
  app/src/main/res/layout/dialog_changepw.xml
  app/src/main/res/layout/dialog_checkpw.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: 기능, 디자인

#44 [U.O.F-Mobile] Exception 추가 및 카드제거 오류 수정
  app/src/main/java/com/uof/uof_mobile/Constants.java
  app/src/main/java/com/uof/uof_mobile/activity/CardActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/LoginActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/RegisterActivity.java
  app/src/main/java/com/uof/uof_mobile/dialog/AddCardDialog.java
  app/src/main/java/com/uof/uof_mobile/dialog/ChangePhoneDialog.java
  app/src/main/java/com/uof/uof_mobile/dialog/ChangePwDialog.java
  app/src/main/java/com/uof/uof_mobile/dialog/CheckPwDialog.java
  app/src/main/java/com/uof/uof_mobile/manager/HttpManager.java
  app/src/main/res/layout/activity_card.xml
  app/src/main/res/values-night/themes.xml
Labels: 오류해결, 기능, 디자인

#45 [U.O.F-Mobile] 회사 종류에 따른 OrderingActivity 생성
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/uof/uof_mobile/Constants.java
  app/src/main/java/com/uof/uof_mobile/activity/IntroActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/MovieOrderingActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/PcOrderingActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/QRRecognitionActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/RegisterActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/RestaurantOrderingActivity.java
  app/src/main/java/com/uof/uof_mobile/manager/PatternManager.java
  app/src/main/res/layout/activity_movieordering.xml
  app/src/main/res/layout/activity_pcordering.xml
  app/src/main/res/layout/activity_restaurantordering.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/dialog_addcard.xml
  app/src/main/res/layout/dialog_changephone.xml
  app/src/main/res/layout/dialog_changepw.xml
  app/src/main/res/layout/dialog_checkpw.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/settings_preference.xml
Labels: 오류해결, 기능, 디자인

#46 [U.O.F-Mobile] 자동로그인 및 네트워크 설정 변경
  app/src/main/java/com/uof/uof_mobile/Constants.java
  app/src/main/java/com/uof/uof_mobile/activity/CardActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/LoginActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/RegisterActivity.java
  app/src/main/java/com/uof/uof_mobile/dialog/AddCardDialog.java
  app/src/main/java/com/uof/uof_mobile/dialog/ChangePhoneDialog.java
  app/src/main/java/com/uof/uof_mobile/dialog/ChangePwDialog.java
  app/src/main/java/com/uof/uof_mobile/dialog/CheckPwDialog.java
  app/src/main/java/com/uof/uof_mobile/fragment/SettingPreferenceFragment.java
  app/src/main/java/com/uof/uof_mobile/manager/SharedPreferenceManager.java
  app/src/main/res/xml/network_security_config.xml
Labels: 기능

#47 [U.O.F-Mobile] RestaurantOrderingActivity 구현(상품) #1
  app/src/main/java/com/uof/uof_mobile/Constants.java
  app/src/main/java/com/uof/uof_mobile/activity/IntroActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/QRRecognitionActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/RegisterActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/RestaurantOrderingActivity.java
  app/src/main/java/com/uof/uof_mobile/dialog/AddCardDialog.java
  app/src/main/java/com/uof/uof_mobile/dialog/ChangePhoneDialog.java
  app/src/main/java/com/uof/uof_mobile/dialog/ChangePwDialog.java
  app/src/main/java/com/uof/uof_mobile/dialog/SelectProductDialog.java
  app/src/main/java/com/uof/uof_mobile/dialog/SelectSetDialog.java
  app/src/main/java/com/uof/uof_mobile/manager/RestaurantBascketManager.java
  app/src/main/java/com/uof/uof_mobile/manager/UsefulFuncManager.java
  app/src/main/java/com/uof/uof_mobile/recyclerview/RestaurantOrderingAdapter.java
  app/src/main/java/com/uof/uof_mobile/recyclerview/RestaurantOrderingCategory.java
  app/src/main/java/com/uof/uof_mobile/recyclerview/RestaurantOrderingProductItem.java
  app/src/main/java/com/uof/uof_mobile/recyclerview/RestaurantOrderingSetItem.java
  app/src/main/res/anim/headdown_fullscreendialog.xml
  app/src/main/res/anim/headup_fullscreendialog.xml
  app/src/main/res/layout/activity_restaurantordering.xml
  app/src/main/res/layout/chip_category.xml
  app/src/main/res/layout/dialog_selectproduct.xml
  app/src/main/res/layout/dialog_selectset.xml
  app/src/main/res/layout/item_restaurantordering_product.xml
  app/src/main/res/layout/item_restaurantordering_set.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: 기능, 디자인, 구현 필요

#48 [U.O.F Mobile] 전반적 디자인 수정
  app/src/main/java/com/uof/uof_mobile/activity/LobbyActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/RegisterActivity.java
  app/src/main/res/drawable/border_registertypedialog.xml
  app/src/main/res/drawable/icon_add_day.png
  app/src/main/res/drawable/icon_add_night.png
  app/src/main/res/drawable/icon_remove_day.png
  app/src/main/res/drawable/icon_remove_night.png
  app/src/main/res/drawable/ripple_cardimage.xml
  app/src/main/res/layout/activity_card.xml
  app/src/main/res/layout/activity_lobby.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/layout/activity_restaurantordering.xml
  app/src/main/res/layout/dialog_addcard.xml
  app/src/main/res/layout/dialog_registertype.xml
  app/src/main/res/layout/dialog_selectproduct.xml
  app/src/main/res/layout/item_restaurantordering_product.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: 디자인, 구성

#50 [U.O.F-Mobile] Hotfix: Constants 클래스명 변경 및 상위 액티비티 종료 오류 해결
  app/src/main/java/com/uof/uof_mobile/Global.java
  app/src/main/java/com/uof/uof_mobile/activity/CardActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/IntroActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/LobbyActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/LoginActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/OrderingActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/QRRecognitionActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/RegisterActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/SettingActivity.java
  app/src/main/java/com/uof/uof_mobile/dialog/AddCardDialog.java
  app/src/main/java/com/uof/uof_mobile/dialog/ChangePhoneDialog.java
  app/src/main/java/com/uof/uof_mobile/dialog/ChangePwDialog.java
  app/src/main/java/com/uof/uof_mobile/dialog/CheckPwDialog.java
  app/src/main/java/com/uof/uof_mobile/fragment/SettingPreferenceFragment.java
  app/src/main/java/com/uof/uof_mobile/manager/HttpManager.java
  app/src/main/java/com/uof/uof_mobile/manager/PatternManager.java
  app/src/main/java/com/uof/uof_mobile/recyclerview/OrderingAdapter.java
  app/src/main/java/com/uof/uof_mobile/recyclerview/OrderingProductItem.java
  app/src/main/java/com/uof/uof_mobile/recyclerview/OrderingSetItem.java
Labels: 오류해결, 수정

#51 [U.O.F-Mobile] Hotfix: 패키지 수정 및 함수 변경
  app/src/main/java/com/uof/uof_mobile/activity/CardActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/IntroActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/LobbyActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/LoginActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/OrderingActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/QRRecognitionActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/RegisterActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/SettingActivity.java
  app/src/main/java/com/uof/uof_mobile/adapter/LobbyListViewItemAdapter.java
  app/src/main/java/com/uof/uof_mobile/adapter/OrderingAdapter.java
  app/src/main/java/com/uof/uof_mobile/adapter/SetProductAdapter.java
  app/src/main/java/com/uof/uof_mobile/dialog/AddCardDialog.java
  app/src/main/java/com/uof/uof_mobile/dialog/ChangePhoneDialog.java
  app/src/main/java/com/uof/uof_mobile/dialog/ChangePwDialog.java
  app/src/main/java/com/uof/uof_mobile/dialog/CheckPwDialog.java
  app/src/main/java/com/uof/uof_mobile/dialog/RegisterTypeDialog.java
  app/src/main/java/com/uof/uof_mobile/dialog/RegisterTypeDialogListener.java
  app/src/main/java/com/uof/uof_mobile/dialog/SelectProductDialog.java
  app/src/main/java/com/uof/uof_mobile/dialog/SelectSetDialog.java
  app/src/main/java/com/uof/uof_mobile/fragment/SettingPreferenceFragment.java
  app/src/main/java/com/uof/uof_mobile/listitem/OrderingItem.java
  app/src/main/java/com/uof/uof_mobile/listitem/OrderingProductItem.java
  app/src/main/java/com/uof/uof_mobile/listitem/OrderingSetItem.java
  app/src/main/java/com/uof/uof_mobile/listview/LobbyListViewItem.java
  app/src/main/java/com/uof/uof_mobile/manager/BasketManager.java
  app/src/main/java/com/uof/uof_mobile/manager/HttpManager.java
  app/src/main/java/com/uof/uof_mobile/manager/PatternManager.java
  app/src/main/java/com/uof/uof_mobile/other/Global.java
  app/src/main/java/com/uof/uof_mobile/other/OrderingCategory.java
Labels: 기능, 수정

#52 [U.O.F-Mobile] 장바구니 다이얼로그 구현
  app/src/main/java/com/uof/uof_mobile/activity/CardActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/IntroActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/LobbyActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/LoginActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/OrderingActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/QRRecognitionActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/RegisterActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/SettingActivity.java
  app/src/main/java/com/uof/uof_mobile/adapter/BasketAdapter.java
  app/src/main/java/com/uof/uof_mobile/adapter/OrderingAdapter.java
  app/src/main/java/com/uof/uof_mobile/adapter/SetProductAdapter.java
  app/src/main/java/com/uof/uof_mobile/dialog/AddCardDialog.java
  app/src/main/java/com/uof/uof_mobile/dialog/BasketDialog.java
  app/src/main/java/com/uof/uof_mobile/dialog/ChangePhoneDialog.java
  app/src/main/java/com/uof/uof_mobile/dialog/ChangePwDialog.java
  app/src/main/java/com/uof/uof_mobile/dialog/CheckPwDialog.java
  app/src/main/java/com/uof/uof_mobile/dialog/SelectProductDialog.java
  app/src/main/java/com/uof/uof_mobile/dialog/SelectSetDialog.java
  app/src/main/java/com/uof/uof_mobile/fragment/SettingPreferenceFragment.java
  app/src/main/java/com/uof/uof_mobile/listitem/OrderingProductItem.java
  app/src/main/java/com/uof/uof_mobile/listitem/OrderingSetItem.java
  app/src/main/java/com/uof/uof_mobile/manager/BasketManager.java
  app/src/main/res/drawable/recyclerview_divider.xml
  app/src/main/res/layout/activity_ordering.xml
  app/src/main/res/layout/dialog_basket.xml
  app/src/main/res/layout/dialog_selectset.xml
  app/src/main/res/layout/item_basket.xml
  app/src/main/res/layout/item_ordering_product.xml
  app/src/main/res/layout/item_ordering_set.xml
  app/src/main/res/layout/item_setproduct.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: 오류해결, 코드 최적화, 기능, 디자인

#53 [U.O.F-Mobile] Hotfix: 장바구니 아이템 삭제 오류 해결
  app/src/main/java/com/uof/uof_mobile/adapter/BasketAdapter.java
Labels: 오류해결, 기능, 수정

#55 [U.O.F-Mobile] PayActivity 구현(주문상품 및 결제 정보 표시) #1
  .gitignore
  app/src/main/java/com/uof/uof_mobile/activity/OrderingActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/PayActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/QRRecognitionActivity.java
  app/src/main/java/com/uof/uof_mobile/adapter/BasketAdapter.java
  app/src/main/java/com/uof/uof_mobile/adapter/PayAdapter.java
  app/src/main/java/com/uof/uof_mobile/adapter/SetProductAdapter.java
  app/src/main/java/com/uof/uof_mobile/dialog/BasketDialog.java
  app/src/main/java/com/uof/uof_mobile/dialog/SelectProductDialog.java
  app/src/main/java/com/uof/uof_mobile/dialog/SelectSetDialog.java
  app/src/main/java/com/uof/uof_mobile/listitem/BasketItem.java
  app/src/main/java/com/uof/uof_mobile/manager/BasketManager.java
  app/src/main/java/com/uof/uof_mobile/other/Global.java
  app/src/main/res/drawable/background_pay_carddisabled.xml
  app/src/main/res/drawable/background_pay_cardenabled.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_pay.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/layout/chip_category.xml
  app/src/main/res/layout/dialog_addcard.xml
  app/src/main/res/layout/dialog_basket.xml
  app/src/main/res/layout/dialog_changephone.xml
  app/src/main/res/layout/dialog_changepw.xml
  app/src/main/res/layout/dialog_checkpw.xml
  app/src/main/res/layout/dialog_registertype.xml
  app/src/main/res/layout/item_pay.xml
  app/src/main/res/layout/item_setproduct.xml
Labels: 오류해결, 코드 최적화, 기능, 디자인, 구현 필요

#56 OrderListActivity 구현
  app/src/main/java/com/uof/uof_mobile/activity/LobbyActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/OrderListActivity.java
  app/src/main/java/com/uof/uof_mobile/adapter/OrderListAdapter.java
  app/src/main/java/com/uof/uof_mobile/listitem/OrderListItem.java
  app/src/main/java/com/uof/uof_mobile/listitem/OrderListProductItem.java
  app/src/main/res/layout/activity_orderlist.xml
  app/src/main/res/layout/item_orderlist_order.xml
Labels: 기능, 디자인, 구현 필요

#58 [U.O.F-Mobile] PayActivity 구현(카드등록 창) #2
  app/src/main/java/com/uof/uof_mobile/activity/CardActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/LoginActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/OrderingActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/PayActivity.java
  app/src/main/java/com/uof/uof_mobile/dialog/AddCardDialog.java
  app/src/main/java/com/uof/uof_mobile/dialog/CardDialog.java
  app/src/main/java/com/uof/uof_mobile/dialog/ChangePhoneDialog.java
  app/src/main/java/com/uof/uof_mobile/dialog/ChangePwDialog.java
  app/src/main/java/com/uof/uof_mobile/fragment/SettingPreferenceFragment.java
  app/src/main/java/com/uof/uof_mobile/manager/BasketManager.java
  app/src/main/java/com/uof/uof_mobile/manager/PatternManager.java
  app/src/main/java/com/uof/uof_mobile/other/Card.java
  app/src/main/java/com/uof/uof_mobile/other/Global.java
  app/src/main/res/drawable/background_button_disabled.xml
  app/src/main/res/drawable/background_button_enabled.xml
  app/src/main/res/drawable/background_pay_cardenabled.xml
  app/src/main/res/layout/activity_card.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_pay.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/layout/dialog_addcard.xml
  app/src/main/res/layout/dialog_card.xml
  app/src/main/res/layout/dialog_changephone.xml
  app/src/main/res/layout/dialog_changepw.xml
  app/src/main/res/layout/dialog_checkpw.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: 기능, 디자인

#60 [U.O.F-Mobile] PayActivity 구현(카드결제) #3
  app/src/main/java/com/uof/uof_mobile/activity/LoginActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/OrderingActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/PayActivity.java
  app/src/main/java/com/uof/uof_mobile/dialog/WaitingOrderDialog.java
  app/src/main/java/com/uof/uof_mobile/other/Global.java
  app/src/main/res/layout/activity_pay.xml
  app/src/main/res/layout/dialog_waitingorder.xml
Labels: 기능, 디자인

#61 [U.O.F Mobile] 파트너 로비 페이지 생성
  app/src/main/java/com/uof/uof_mobile/activity/LoginActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/OwnerLobbyActivity.java
  app/src/main/java/com/uof/uof_mobile/dialog/ShowQRDialog.java
  app/src/main/res/layout/activity_ownerlobby.xml
  app/src/main/res/layout/dialog_showqr.xml
Labels: 기능, 디자인, 구성

#62 [U.O.F-Mobile] 영화관 자리선택 및 상품 주문화면 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/uof/uof_mobile/activity/LoginActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/MovieOrderingActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/OrderListActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/OrderingActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/OwnerLobbyActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/PayActivity.java
  app/src/main/java/com/uof/uof_mobile/activity/QRRecognitionActivity.java
  app/src/main/java/com/uof/uof_mobile/adapter/BasketAdapter.java
  app/src/main/java/com/uof/uof_mobile/adapter/MovieOrderingAdapter.java
  app/src/main/java/com/uof/uof_mobile/adapter/MovieSeatAdapter.java
  app/src/main/java/com/uof/uof_mobile/adapter/OrderListAdapter.java
  app/src/main/java/com/uof/uof_mobile/adapter/PayAdapter.java
  app/src/main/java/com/uof/uof_mobile/dialog/CardDialog.java
  app/src/main/java/com/uof/uof_mobile/dialog/ChangePhoneDialog.java
  app/src/main/java/com/uof/uof_mobile/dialog/ChangePwDialog.java
  app/src/main/java/com/uof/uof_mobile/dialog/SelectProductDialog.java
  app/src/main/java/com/uof/uof_mobile/dialog/SelectSeatDialog.java
  app/src/main/java/com/uof/uof_mobile/dialog/SelectSetDialog.java
  app/src/main/java/com/uof/uof_mobile/dialog/ShowQRDialog.java
  app/src/main/java/com/uof/uof_mobile/dialog/WaitingOrderDialog.java
  app/src/main/java/com/uof/uof_mobile/fragment/SettingPreferenceFragment.java
  app/src/main/java/com/uof/uof_mobile/listitem/BasketItem.java
  app/src/main/java/com/uof/uof_mobile/listitem/MovieItem.java
  app/src/main/java/com/uof/uof_mobile/listitem/MovieSeatItem.java
  app/src/main/java/com/uof/uof_mobile/listitem/OrderListItem.java
  app/src/main/java/com/uof/uof_mobile/listitem/OrderListProductItem.java
  app/src/main/java/com/uof/uof_mobile/other/Card.java
  app/src/main/java/com/uof/uof_mobile/other/Global.java
  app/src/main/res/drawable/border_seat_alreadyreserved.xml
  app/src/main/res/drawable/border_seat_reservationavailable.xml
  app/src/main/res/drawable/border_seat_selectedseat.xml
  app/src/main/res/drawable/border_seat_unreservedseat.xml
  app/src/main/res/font/custom_font.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_movieordering.xml
  app/src/main/res/layout/activity_ordering.xml
  app/src/main/res/layout/activity_orderlist.xml
  app/src/main/res/layout/activity_ownerlobby.xml
  app/src/main/res/layout/activity_pay.xml
  app/src/main/res/layout/dialog_changephone.xml
  app/src/main/res/layout/dialog_changepw.xml
  app/src/main/res/layout/dialog_checkpw.xml
  app/src/main/res/layout/dialog_selectseat.xml
  app/src/main/res/layout/dialog_selectset.xml
  app/src/main/res/layout/dialog_showqr.xml
  app/src/main/res/layout/item_basket.xml
  app/src/main/res/layout/item_movieordering.xml
  app/src/main/res/layout/item_pay.xml
  app/src/main/res/layout/item_seat_alreadyreserved.xml
  app/src/main/res/layout/item_seat_none.xml
  app/src/main/res/layout/item_seat_reservationavailable.xml
  app/src/main/res/layout/item_seat_selectedseat.xml
  app/src/main/res/layout/item_seat_unreservedseat.xml
  app/src/main/res/layout/rows_noworderlist.xml
Labels: 오류해결, 코드 최적화, 기능, 디자인, 구현 필요, 라이브러리
