Repository UOS2021/U.O.S-Mobile, pull requests merged in 2021-07, with the labels that each got.

#2 Modify main text
  app/src/main/res/layout/activity_main.xml
Labels: 변경사항

#3 안드로이드 소켓 통신 구현
  app/src/main/java/com/uof/uof_mobile/Constants.java
  app/src/main/java/com/uof/uof_mobile/UofSocket.java
Labels: enhancement

#4 안드로이드 소켓 테스팅 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/uof/uof_mobile/MainActivity.java
  app/src/main/java/com/uof/uof_mobile/SocketTestActivity.java
  app/src/main/java/com/uof/uof_mobile/UofSocket.java
  app/src/main/res/layout/activity_sockettest.xml
Labels: enhancement

#5 안드로이드 QR코드 인식 및 UOF-Mobile 앱 실행
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/uof/uof_mobile/MainActivity.java
  app/src/main/java/com/uof/uof_mobile/SocketTestActivity.java
Labels: enhancement

#6 안드로이드 클라이언트 <-> 서버 소켓 통신 오류 수정
  app/src/main/java/com/uof/uof_mobile/Constants.java
  app/src/main/java/com/uof/uof_mobile/SocketTestActivity.java
  app/src/main/java/com/uof/uof_mobile/UofSocket.java
Labels: fix bug

#7 안드로이드 클라이언트 <-> 서버 소켓 통신 오류 수정 (2)
  app/src/main/java/com/uof/uof_mobile/SocketTestActivity.java
Labels: fix bug

#9 안드로이드 스튜디오 업데이트
  .idea/gradle.xml
  .idea/misc.xml
  .idea/runConfigurations.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: 개발환경, 오류

#12 U.O.F-Mobile 구성 Activity 추가
  .idea/misc.xml
  .idea/render.experimental.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/uof/uof_mobile/CardActivity.java
  app/src/main/java/com/uof/uof_mobile/IntroActivity.java
  app/src/main/java/com/uof/uof_mobile/LobbyActivity.java
  app/src/main/java/com/uof/uof_mobile/LoginActivity.java
  app/src/main/java/com/uof/uof_mobile/OrderListActivity.java
  app/src/main/java/com/uof/uof_mobile/OrderingActivity.java
  app/src/main/java/com/uof/uof_mobile/PayActivity.java
  app/src/main/java/com/uof/uof_mobile/QRRecognitionActivity.java
  app/src/main/java/com/uof/uof_mobile/SettingActivity.java
  app/src/main/res/layout/activity_card.xml
  app/src/main/res/layout/activity_intro.xml
  app/src/main/res/layout/activity_lobby.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_order_list.xml
  app/src/main/res/layout/activity_ordering.xml
  app/src/main/res/layout/activity_pay.xml
  app/src/main/res/layout/activity_qrrecognition.xml
  app/src/main/res/layout/activity_setting.xml
Labels: 기능, 디자인
